name: jl
favicon: null
layout_spectrum: 0.7562
typography_spectrum: 0.74309
title: Jacob Lindberg
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.75
  lightness: 0.9375
  saturation: 0.4297596891410649
  rhythmicContrast: 0.5
purpose: []
